import { MigrationInterface, QueryRunner } from "typeorm";

export class MockData1601184088518 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      insert into neighborhood (name) values ('Sugar glider');
insert into neighborhood (name) values ('Common wallaroo');
insert into neighborhood (name) values ('Dove, mourning collared');
insert into neighborhood (name) values ('Legaan, water');
insert into neighborhood (name) values ('African elephant');
insert into neighborhood (name) values ('Scarlet macaw');
insert into neighborhood (name) values ('Dolphin, striped');
insert into neighborhood (name) values ('Goose, spur-winged');
insert into neighborhood (name) values ('White-rumped vulture');
insert into neighborhood (name) values ('African wild cat');
insert into neighborhood (name) values ('Swainson''s francolin');
insert into neighborhood (name) values ('Turkey, common');
insert into neighborhood (name) values ('Wildebeest, blue');
insert into neighborhood (name) values ('Tarantula, salmon pink bird eater');
insert into neighborhood (name) values ('White-mantled colobus');
insert into neighborhood (name) values ('Magpie, australian');
insert into neighborhood (name) values ('Emu');
insert into neighborhood (name) values ('Snowy egret');
insert into neighborhood (name) values ('Capuchin, black-capped');
insert into neighborhood (name) values ('Puffin, horned');
insert into neighborhood (name) values ('Polar bear');
insert into neighborhood (name) values ('Bush dog');
insert into neighborhood (name) values ('South American meadowlark (unidentified)');
insert into neighborhood (name) values ('Tortoise, burmese black mountain');
insert into neighborhood (name) values ('Springbuck');
insert into neighborhood (name) values ('Lizard, desert spiny');
insert into neighborhood (name) values ('Great horned owl');
insert into neighborhood (name) values ('Stork, woolly-necked');
insert into neighborhood (name) values ('Phalarope, grey');
insert into neighborhood (name) values ('Bear, sloth');
insert into neighborhood (name) values ('Long-tailed jaeger');
insert into neighborhood (name) values ('Black-tailed tree creeper');
insert into neighborhood (name) values ('Vulture, white-rumped');
insert into neighborhood (name) values ('Brush-tailed phascogale');
insert into neighborhood (name) values ('Lapwing (unidentified)');
insert into neighborhood (name) values ('Partridge, coqui');
insert into neighborhood (name) values ('Northern fur seal');
insert into neighborhood (name) values ('Yellow baboon');
insert into neighborhood (name) values ('Fox, arctic');
insert into neighborhood (name) values ('Chestnut weaver');
insert into neighborhood (name) values ('Egret, snowy');
insert into neighborhood (name) values ('Salmon pink bird eater tarantula');
insert into neighborhood (name) values ('Jungle kangaroo');
insert into neighborhood (name) values ('Dove, laughing');
insert into neighborhood (name) values ('Cat, cape wild');
insert into neighborhood (name) values ('Blue peacock');
insert into neighborhood (name) values ('Cat, jungle');
insert into neighborhood (name) values ('Southern elephant seal');
insert into neighborhood (name) values ('Praying mantis (unidentified)');
insert into neighborhood (name) values ('Bald eagle');
insert into neighborhood (name) values ('Butterfly, tropical buckeye');
insert into neighborhood (name) values ('Long-billed corella');
insert into neighborhood (name) values ('American racer');
insert into neighborhood (name) values ('Griffon vulture');
insert into neighborhood (name) values ('Waxbill, blue');
insert into neighborhood (name) values ('Bent-toed gecko');
insert into neighborhood (name) values ('Owl, australian masked');
insert into neighborhood (name) values ('Green heron');
insert into neighborhood (name) values ('Eagle, long-crested hawk');
insert into neighborhood (name) values ('Coqui francolin');
insert into neighborhood (name) values ('Francolin, swainson''s');
insert into neighborhood (name) values ('Manatee');
insert into neighborhood (name) values ('Black-necked stork');
insert into neighborhood (name) values ('Kalahari scrub robin');
insert into neighborhood (name) values ('Quail, gambel''s');
insert into neighborhood (name) values ('Fairy penguin');
insert into neighborhood (name) values ('Saddle-billed stork');
insert into neighborhood (name) values ('Australian spiny anteater');
insert into neighborhood (name) values ('Heron, green');
insert into neighborhood (name) values ('Green-winged macaw');
insert into neighborhood (name) values ('Turtle, long-necked');
insert into neighborhood (name) values ('Porcupine, prehensile-tailed');
insert into neighborhood (name) values ('Lion, asian');
insert into neighborhood (name) values ('Penguin, fairy');
insert into neighborhood (name) values ('Flamingo, lesser');
insert into neighborhood (name) values ('Bleu, blue-breasted cordon');
insert into neighborhood (name) values ('Civet (unidentified)');
insert into neighborhood (name) values ('Mudskipper (unidentified)');
insert into neighborhood (name) values ('Nelson ground squirrel');
insert into neighborhood (name) values ('Rufous tree pie');
insert into neighborhood (name) values ('River wallaby');
insert into neighborhood (name) values ('Macaque, rhesus');
insert into neighborhood (name) values ('Tortoise, burmese brown mountain');
insert into neighborhood (name) values ('Stork, black-necked');
insert into neighborhood (name) values ('Ox, musk');
insert into neighborhood (name) values ('Greater sage grouse');
insert into neighborhood (name) values ('Duiker, common');
insert into neighborhood (name) values ('White-cheeked pintail');
insert into neighborhood (name) values ('Iguana, common green');
insert into neighborhood (name) values ('Lion, african');
insert into neighborhood (name) values ('Black-necked flinston');
insert into neighborhood (name) values ('Paca');
insert into neighborhood (name) values ('Kangaroo, jungle');
insert into neighborhood (name) values ('Egyptian goose');
insert into neighborhood (name) values ('African lynx');
insert into neighborhood (name) values ('Lava gull');
insert into neighborhood (name) values ('Brown and yellow marshbird');
insert into neighborhood (name) values ('Egret, great');
insert into neighborhood (name) values ('Hawk-eagle, crowned');
insert into neighborhood (name) values ('Black-footed ferret');
`);
  }

  public async down(_: QueryRunner): Promise<void> {}
}
